package com.toandfrom.toandfrom.controller;

import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * 시각화 이미지 제공 컨트롤러
 * Visualization Controller for serving generated images
 * 
 * Python 스크립트(Flask)에서 생성한 시각화 이미지를 제공합니다.
 * Provides visualization images generated by Python scripts (Flask).
 * 
 * @author QuantaFolio Navigator Team
 * @version 1.0.0
 * @since 2025-11-10
 */
@RestController
@RequestMapping("/api/visualizations")
@CrossOrigin(origins = "http://localhost:5173")
public class VisualizationController {
    
    /**
     * 시각화 이미지 파일 제공
     * Serve visualization image file
     * 
     * @param filename 이미지 파일명 (예: portfolio_chart.png)
     * @return 이미지 리소스 (PNG 형식)
     */
    @GetMapping("/{filename}")
    public ResponseEntity<Resource> getVisualization(@PathVariable String filename) {
        try {
            // Flask output 디렉토리 경로
            // Flask output directory path
            Path filePath = Paths.get("python-backend/output/" + filename);
            Resource resource = new FileSystemResource(filePath);
            
            if (resource.exists() && resource.isReadable()) {
                return ResponseEntity.ok()
                    .contentType(MediaType.IMAGE_PNG)
                    .header(HttpHeaders.CONTENT_DISPOSITION, 
                        "inline; filename=\"" + filename + "\"")
                    .body(resource);
            } else {
                System.err.println("Visualization file not found: " + filePath.toAbsolutePath());
                return ResponseEntity.notFound().build();
            }
        } catch (Exception e) {
            System.err.println("Error serving visualization: " + e.getMessage());
            e.printStackTrace();
            return ResponseEntity.internalServerError().build();
        }
    }
    
    /**
     * 시각화 이미지 목록 조회 (선택적)
     * Get list of available visualization images (optional)
     * 
     * @return 이미지 파일명 목록
     */
    @GetMapping("/list")
    public ResponseEntity<?> listVisualizations() {
        try {
            Path outputDir = Paths.get("python-backend/output/");
            if (!outputDir.toFile().exists()) {
                return ResponseEntity.ok().body(new String[]{"No output directory found"});
            }
            
            // 간단한 구현: 실제로는 디렉토리 스캔 필요
            // Simple implementation: actual directory scanning needed
            return ResponseEntity.ok().body(new String[]{"Visualization list endpoint - to be implemented"});
        } catch (Exception e) {
            System.err.println("Error listing visualizations: " + e.getMessage());
            return ResponseEntity.internalServerError().build();
        }
    }
}

